# Generated by Django 4.1.6 on 2023-02-06 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
